#!/usr/bin/env bash

BLANK='#26233a'
CLEAR='#26233a'
DEFAULT='#ebbcba'
TEXT='#9ccfd8'
WRONG='#eb6f92'
VERIFYING='#31748f'

PICTURE="/tmp/screen_locked.png"
scrot /tmp/screen_locked.png
mogrify -sample 25% -scale 400% $PICTURE

i3lock -i $PICTURE \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$CLEAR         \
--bshl-color=$WRONG          \
\
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%d.%m.%Y"        \

rm $PICTURE
