#
# ~/.config/helix/config.toml
#

theme = "rose_pine"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "underline"
normal = "block"

[editor.file-picker]
hidden = false

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.lsp]
display-messages = true

[keys.normal]
"ret" = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
